name: Bug Report
description: Report a feature that is not working as expected.
labels: [Bug]
body:
  - type: textarea
    id: describe
    attributes:
      label: Describe the bug
      description: A clear and concise description of the issue.
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Add screenshots to illustrate the issue.
    validations:
      required: false
  - type: dropdown
    id: location
    attributes:
      label: Where does this issue occur?
      multiple: true
      options:
        - "Github"
        - "Discord"
        - "External tool"
        - "Other"
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
    validations:
      required: false