name: Release Notifications

on:
  workflow_dispatch:
  push:
    paths:
      - 'manifest.json'
    branches:
      - main

jobs:
  Release-Notifications:
    if: github.repository == 'resonite-modding-group/resonite-mod-manifest'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "pip"

      - run: pip install -r requirements.txt

      - name: Generate notification json
        id: gen
        env:
          REF_BASE: ${{ github.base_ref || format('{0}~', github.sha) }}
          REF_NEW: ${{ github.head_ref || github.sha }}
        run: python3 generate_notification.py

      - name: Send notification
        if: ${{ steps.gen.outputs.JSON != '' }}
        run: "curl --fail -H 'Content-Type: application/json' -d '${{ steps.gen.outputs.JSON }}' '${{ secrets.DISCORD_MOD_RELEASES_WEBHOOK_URL }}'"